pub mod adapters;
pub mod api;
pub mod classifier;
pub mod classification;
pub mod decode;
pub mod entities;
pub mod embeddings;
pub mod encoder;
pub mod extractor;
pub mod json;
pub mod pipeline;
pub mod relations;
pub mod schema;
pub mod schema_spec;
pub mod spans;
pub mod structures;
pub mod text;
pub mod tokenizer;
pub mod training;
pub mod validators;

pub type Result<T> = anyhow::Result<T>;
